package com.coolcloud.sacw.person.entity;

import java.util.Date;

import com.coolcloud.sacw.common.BaseEntity;

/**
 * 案件相关人员信息表
 * @author 王腾飞
 *2018年12月28日上午10:55:47
 */
public class Person extends BaseEntity {

	private static final long serialVersionUID = 2502388739274434272L;

	/**
	 * 案件id
	 */
	private String caseId;

	/**
	 * Database Column Remarks: 平台案件编号
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.plat_case_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String platCaseCode;

	/**
	 * Database Column Remarks: 平台人员编号
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.plat_person_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String platPersonCode;

	/**
	 * Database Column Remarks: 人员姓名
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.person_name
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String personName;

	/**
	 * Database Column Remarks: 国籍
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.nation
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String nation;

	/**
	 * Database Column Remarks: 国籍编码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.nation_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String nationCode;

	/**
	 * Database Column Remarks: 籍贯
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.native_place
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String nativePlace;

	/**
	 * Database Column Remarks: 籍贯编码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.native_place_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String nativePlaceCode;

	/**
	 * Database Column Remarks: 人员类型
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.person_type
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String personType;

	/**
	 * Database Column Remarks: 人员类别
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.person_class
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String personClass;

	/**
	 * Database Column Remarks: 组织机构代码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.org_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String orgCode;

	/**
	 * Database Column Remarks: 组织机构名称
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.org_name
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String orgName;

	/**
	 * Database Column Remarks: 单位所在地
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.unit_address
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String unitAddress;

	/**
	 * Database Column Remarks: 罪名
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.crime_name
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String crimeName;

	/**
	 * Database Column Remarks: 罪名编码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.crime_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String crimeCode;

	/**
	 * Database Column Remarks: 性别编码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.gender_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String genderCode;

	/**
	 * Database Column Remarks: 性别名称
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.gender
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String gender;

	/**
	 * Database Column Remarks: 出生日期
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.birthday
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private Date birthday;

	/**
	 * Database Column Remarks: 证件类型
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.id_type
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String idType;

	/**
	 * Database Column Remarks: 证件类型编码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.id_type_code
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String idTypeCode;

	/**
	 * Database Column Remarks: 证件号码
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.id_number
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String idNumber;

	/**
	 * Database Column Remarks: 住所地
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.address
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String address;

	/**
	 * Database Column Remarks: 案发地
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.venue
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String venue;

	/**
	 * Database Column Remarks: 联系电话
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.phone_number
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String phoneNumber;

	/**
	 * Database Column Remarks: 备注
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.remark
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private String remark;

	/**
	 * Database Column Remarks: 登记日期
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column yw_person.record_date
	 *
	 * @mbg.generated Tue Aug 22 20:21:18 CST 2017
	 */
	private Date recordDate;

	public String getCaseId() {
		return caseId;
	}

	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	public String getPlatCaseCode() {
		return platCaseCode;
	}

	public void setPlatCaseCode(String platCaseCode) {
		this.platCaseCode = platCaseCode;
	}

	public String getPlatPersonCode() {
		return platPersonCode;
	}

	public void setPlatPersonCode(String platPersonCode) {
		this.platPersonCode = platPersonCode;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	public String getNationCode() {
		return nationCode;
	}

	public void setNationCode(String nationCode) {
		this.nationCode = nationCode;
	}

	public String getNativePlace() {
		return nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	public String getNativePlaceCode() {
		return nativePlaceCode;
	}

	public void setNativePlaceCode(String nativePlaceCode) {
		this.nativePlaceCode = nativePlaceCode;
	}

	public String getPersonType() {
		return personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	public String getPersonClass() {
		return personClass;
	}

	public void setPersonClass(String personClass) {
		this.personClass = personClass;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getUnitAddress() {
		return unitAddress;
	}

	public void setUnitAddress(String unitAddress) {
		this.unitAddress = unitAddress;
	}

	public String getCrimeName() {
		return crimeName;
	}

	public void setCrimeName(String crimeName) {
		this.crimeName = crimeName;
	}

	public String getCrimeCode() {
		return crimeCode;
	}

	public void setCrimeCode(String crimeCode) {
		this.crimeCode = crimeCode;
	}

	public String getGenderCode() {
		return genderCode;
	}

	public void setGenderCode(String genderCode) {
		this.genderCode = genderCode;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getIdType() {
		return idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

	public String getIdTypeCode() {
		return idTypeCode;
	}

	public void setIdTypeCode(String idTypeCode) {
		this.idTypeCode = idTypeCode;
	}

	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getVenue() {
		return venue;
	}

	public void setVenue(String venue) {
		this.venue = venue;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getRecordDate() {
		return recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

}